CREATE TABLE ACT_FO_FORM_DEPLOYMENT (ID_ varchar(255) NOT NULL, NAME_ nvarchar(255), CATEGORY_ varchar(255), DEPLOY_TIME_ datetime, TENANT_ID_ varchar(255), PARENT_DEPLOYMENT_ID_ varchar(255), CONSTRAINT PK_ACT_FO_FORM_DEPLOYMENT PRIMARY KEY (ID_));

CREATE TABLE ACT_FO_FORM_RESOURCE (ID_ varchar(255) NOT NULL, NAME_ nvarchar(255), DEPLOYMENT_ID_ varchar(255), RESOURCE_BYTES_ varbinary(MAX), CONSTRAINT PK_ACT_FO_FORM_RESOURCE PRIMARY KEY (ID_));

CREATE TABLE ACT_FO_FORM_DEFINITION (ID_ varchar(255) NOT NULL, NAME_ nvarchar(255), VERSION_ int, KEY_ varchar(255), CATEGORY_ varchar(255), DEPLOYMENT_ID_ varchar(255), TENANT_ID_ varchar(255), RESOURCE_NAME_ nvarchar(255), DESCRIPTION_ nvarchar(255), CONSTRAINT PK_ACT_FO_FORM_DEFINITION PRIMARY KEY (ID_));

CREATE TABLE ACT_FO_FORM_INSTANCE (ID_ varchar(255) NOT NULL, FORM_DEFINITION_ID_ varchar(255), TASK_ID_ varchar(255), PROC_INST_ID_ varchar(255), PROC_DEF_ID_ varchar(255), SCOPE_ID_ varchar(255), SCOPE_TYPE_ varchar(255), SCOPE_DEFINITION_ID_ varchar(255), SUBMITTED_DATE_ datetime, SUBMITTED_BY_ varchar(255), FORM_VALUES_ID_ varchar(255), TENANT_ID_ varchar(255), CONSTRAINT PK_ACT_FO_FORM_INSTANCE PRIMARY KEY (ID_));

CREATE NONCLUSTERED INDEX ACT_IDX_FORM_RSRC_DPL ON ACT_FO_FORM_RESOURCE (DEPLOYMENT_ID_);

CREATE UNIQUE NONCLUSTERED INDEX ACT_IDX_FORM_DEF_UNIQ ON ACT_FO_FORM_DEFINITION (KEY_, VERSION_, TENANT_ID_);

CREATE NONCLUSTERED INDEX ACT_IDX_FORM_TASK ON ACT_FO_FORM_INSTANCE (TASK_ID_);

CREATE NONCLUSTERED INDEX ACT_IDX_FORM_PROC ON ACT_FO_FORM_INSTANCE (PROC_INST_ID_);

CREATE NONCLUSTERED INDEX ACT_IDX_FORM_SCOPE ON ACT_FO_FORM_INSTANCE (SCOPE_ID_, SCOPE_TYPE_);

insert into ACT_GE_PROPERTY
values ('form.schema.version', '8.1.0.1', 1);
