/* Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.flowable.cmmn.test.togetherflow;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;
import java.util.stream.Collectors;

import org.flowable.cmmn.api.repository.CaseDefinition;
import org.flowable.cmmn.api.repository.CmmnDeployment;
import org.flowable.cmmn.model.Case;
import org.flowable.cmmn.model.CasePageTask;
import org.flowable.cmmn.model.CmmnModel;
import org.flowable.cmmn.model.ExternalWorkerServiceTask;
import org.flowable.cmmn.model.HttpServiceTask;
import org.flowable.cmmn.model.IntentEventListener;
import org.flowable.cmmn.model.Milestone;
import org.flowable.cmmn.model.PlanFragment;
import org.flowable.cmmn.model.PlanItemDefinition;
import org.flowable.cmmn.model.ReactivateEventListener;
import org.flowable.cmmn.model.ScriptServiceTask;
import org.flowable.cmmn.model.SendEventServiceTask;
import org.flowable.cmmn.model.ServiceTask;
import org.flowable.cmmn.model.SignalEventListener;
import org.flowable.cmmn.model.Stage;
import org.flowable.cmmn.model.TimerEventListener;
import org.flowable.cmmn.model.UserEventListener;
import org.flowable.cmmn.model.VariableEventListener;
import org.flowable.cmmn.test.FlowableCmmnTestCase;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;

/**
 * Does the case model TogetherFlow's designer writes actually deploy?
 *
 * <p>The design module has a hand-written CMMN serialiser — not bpmn-js, not this
 * repository's own exporter — and it checks its output against {@code CMMN11.xsd} with
 * {@code xmllint}. That is the gate a deployment runs <em>first</em>, and it is a real
 * check: four earlier versions of that serialiser produced documents the schema rejected.
 * But it is only the first gate. The parser and {@code CaseValidator} run after it, and
 * neither is exercised by validating XML in a browser toolchain.
 *
 * <p>So this deploys the same document, into a real engine. It is checked in at
 * {@code org/flowable/cmmn/test/togetherflow/design-kitchen-sink.cmmn} and generated by
 * the designer's own code; {@code schemaValidity.test.ts} fails if the two drift, so
 * neither side can quietly start testing a different case.
 *
 * <p>The case uses every plan item kind the designer can draw and every setting its
 * properties panel can author — twenty-one kinds, including the six typed tasks and the
 * four typed event listeners, which are the ones that carry a {@code flowable:} discriminator
 * rather than being an element of their own.
 *
 * <p><strong>Why this test lives in an upstream module.</strong> It needs the CMMN engine
 * and its test harness, and it has to run in the default build rather than behind a
 * profile — a check that does not run reports nothing. It touches no main code.
 */
public class TogetherFlowGeneratedCaseTest extends FlowableCmmnTestCase {

    private static final String RESOURCE = "org/flowable/cmmn/test/togetherflow/design-kitchen-sink.cmmn";

    /** Every kind the designer's palette can draw, by its definition id in the fixture. */
    private static final List<String> EXPECTED_DEFINITIONS = List.of(
            "humanTask", "processTask", "caseTask", "decisionTask", "serviceTask",
            "scriptTask", "httpTask", "mailTask", "externalWorkerTask", "casePageTask",
            "sendEventTask", "milestone", "stage", "planFragment",
            "timerEventListener", "userEventListener", "genericEventListener",
            "signalEventListener", "variableEventListener", "intentEventListener",
            "reactivateEventListener",
            // Inside the stage and inside the plan fragment. A fragment's definitions belong
            // to the enclosing stage, per the schema, so these are found in different places
            // and are here to prove both are reached.
            "insideStage", "insideFragment");

    @AfterEach
    public void deleteDeployments() {
        for (CmmnDeployment deployment : cmmnRepositoryService.createDeploymentQuery().list()) {
            cmmnRepositoryService.deleteDeployment(deployment.getId(), true);
        }
    }

    /**
     * The whole point. A deploy runs schema validation, then the parser, then
     * {@code CaseValidator}; anything any of them refuses throws here.
     */
    @Test
    public void deploys() {
        String deploymentId = deploy();

        CaseDefinition definition = cmmnRepositoryService.createCaseDefinitionQuery()
                .deploymentId(deploymentId).singleResult();

        assertThat(definition).isNotNull();
        assertThat(definition.getKey()).isEqualTo("kitchenSink");
        assertThat(definition.getName()).isEqualTo("Kitchen sink");
    }

    /**
     * Deploying is not the same as being understood. A plan item definition the parser did
     * not recognise is skipped rather than rejected, so the case would deploy with the
     * element quietly missing — which is how a designer ships a shape that draws and does
     * nothing.
     */
    @Test
    public void keepsEveryKindTheDesignerCanDraw() {
        CmmnModel model = cmmnRepositoryService.getCmmnModel(caseDefinitionId(deploy()));
        Case caze = model.getPrimaryCase();

        List<String> found = allDefinitionIds(caze.getPlanModel());

        assertThat(found).containsAll(EXPECTED_DEFINITIONS);
    }

    /**
     * Deploying is still not the same as being understood.
     *
     * <p>Six of the designer's task kinds and four of its listeners are not elements of
     * their own: they are a {@code <task>} or an {@code <eventListener>} carrying a
     * {@code flowable:} discriminator. Get that discriminator wrong and the document is
     * still valid, still deploys, and still contains the shape — as a plain {@code Task}
     * that does nothing, which no other check here would notice.
     *
     * <p>So this asserts the class the parser actually built. It is the end-to-end proof
     * that the designer's type and the engine's type are the same thing.
     */
    @Test
    public void buildsTheSpecificKindForEachDiscriminator() {
        CmmnModel model = cmmnRepositoryService.getCmmnModel(caseDefinitionId(deploy()));
        Map<String, PlanItemDefinition> byId = definitionsById(model.getPrimaryCase().getPlanModel());

        assertThat(byId.get("scriptTask")).isInstanceOf(ScriptServiceTask.class);
        assertThat(byId.get("httpTask")).isInstanceOf(HttpServiceTask.class);
        assertThat(byId.get("externalWorkerTask")).isInstanceOf(ExternalWorkerServiceTask.class);
        assertThat(byId.get("casePageTask")).isInstanceOf(CasePageTask.class);
        assertThat(byId.get("sendEventTask")).isInstanceOf(SendEventServiceTask.class);
        assertThat(byId.get("signalEventListener")).isInstanceOf(SignalEventListener.class);
        assertThat(byId.get("variableEventListener")).isInstanceOf(VariableEventListener.class);
        assertThat(byId.get("intentEventListener")).isInstanceOf(IntentEventListener.class);
        assertThat(byId.get("reactivateEventListener")).isInstanceOf(ReactivateEventListener.class);

        assertThat(byId.get("timerEventListener")).isInstanceOf(TimerEventListener.class);
        assertThat(byId.get("userEventListener")).isInstanceOf(UserEventListener.class);
        assertThat(byId.get("milestone")).isInstanceOf(Milestone.class);
        assertThat(byId.get("stage")).isInstanceOf(Stage.class);
        assertThat(byId.get("planFragment")).isInstanceOf(PlanFragment.class);

        // A mail task has no class of its own: it is a ServiceTask whose type says so.
        assertThat(byId.get("mailTask")).isInstanceOfSatisfying(ServiceTask.class,
                task -> assertThat(task.getType()).isEqualTo(ServiceTask.MAIL_TASK));
    }

    /**
     * The settings the panel writes have to survive as more than attributes on a bag: the
     * parser has to have read them onto the model object the behaviour uses.
     */
    @Test
    public void readsTheSettingsTheDesignerWrote() {
        CmmnModel model = cmmnRepositoryService.getCmmnModel(caseDefinitionId(deploy()));
        Map<String, PlanItemDefinition> byId = definitionsById(model.getPrimaryCase().getPlanModel());

        assertThat(byId.get("scriptTask")).isInstanceOfSatisfying(ScriptServiceTask.class, script -> {
            assertThat(script.getScriptFormat()).isEqualTo("groovy");
            assertThat(script.getResultVariableName()).isEqualTo("total");
            assertThat(script.getScript()).isEqualTo("return 1 + 1");
        });

        assertThat(byId.get("externalWorkerTask")).isInstanceOfSatisfying(
                ExternalWorkerServiceTask.class,
                worker -> assertThat(worker.getTopic()).isEqualTo("orderPicking"));

        assertThat(byId.get("casePageTask")).isInstanceOfSatisfying(CasePageTask.class, page -> {
            assertThat(page.getFormKey()).isEqualTo("overview");
            assertThat(page.getLabel()).isEqualTo("Overview");
            assertThat(page.getIcon()).isEqualTo("chart");
        });

        assertThat(byId.get("signalEventListener")).isInstanceOfSatisfying(
                SignalEventListener.class,
                signal -> assertThat(signal.getSignalRef()).isEqualTo("somethingHappened"));

        assertThat(byId.get("variableEventListener")).isInstanceOfSatisfying(
                VariableEventListener.class, variable -> {
                    assertThat(variable.getVariableName()).isEqualTo("amount");
                    assertThat(variable.getVariableChangeType()).isEqualTo("update");
                });

        assertThat(byId.get("timerEventListener")).isInstanceOfSatisfying(
                TimerEventListener.class, timer -> {
                    assertThat(timer.getTimerExpression()).isEqualTo("PT1H");
                    // The start trigger: what starts the clock, not when it fires.
                    assertThat(timer.getTimerStartTriggerSourceRef()).isNotBlank();
                });
    }

    private String deploy() {
        return cmmnRepositoryService.createDeployment().addClasspathResource(RESOURCE).deploy().getId();
    }

    private String caseDefinitionId(String deploymentId) {
        return cmmnRepositoryService.createCaseDefinitionQuery()
                .deploymentId(deploymentId).singleResult().getId();
    }

    /** Definition ids in this stage and, recursively, in every stage and fragment inside it. */
    private static List<String> allDefinitionIds(Stage stage) {
        return List.copyOf(definitionsById(stage).keySet());
    }

    /**
     * Every plan item definition reachable from this stage, by id.
     *
     * <p>Recursive because a plan fragment holds plan items whose definitions belong to the
     * enclosing stage, and a nested stage holds its own — so a flat read of the plan model
     * finds some of them and not others.
     */
    private static Map<String, PlanItemDefinition> definitionsById(Stage stage) {
        return flatten(stage).stream().collect(Collectors.toMap(
                PlanItemDefinition::getId, definition -> definition, (first, second) -> first));
    }

    private static List<PlanItemDefinition> flatten(Stage stage) {
        List<PlanItemDefinition> all = new ArrayList<>();
        Consumer<PlanItemDefinition> add = definition -> {
            all.add(definition);
            if (definition instanceof Stage nested) {
                all.addAll(flatten(nested));
            }
        };
        stage.getPlanItemDefinitions().forEach(add);
        return all;
    }
}
