IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ACT_IDX_FORM_RSRC_DPL') drop index ACT_FO_FORM_RESOURCE.ACT_IDX_FORM_RSRC_DPL;
IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ACT_IDX_FORM_DEF_UNIQ') drop index ACT_FO_FORM_DEFINITION.ACT_IDX_FORM_DEF_UNIQ;
IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ACT_IDX_FORM_TASK') drop index ACT_FO_FORM_INSTANCE.ACT_IDX_FORM_TASK;
IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ACT_IDX_FORM_PROC') drop index ACT_FO_FORM_INSTANCE.ACT_IDX_FORM_PROC;
IF EXISTS (SELECT name FROM sysindexes WHERE name = 'ACT_IDX_FORM_SCOPE') drop index ACT_FO_FORM_INSTANCE.ACT_IDX_FORM_SCOPE;

if exists (select TABLE_NAME from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'ACT_FO_FORM_RESOURCE') if exists (select TABLE_NAME from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'ACT_FO_FORM_INSTANCE') drop table ACT_FO_FORM_INSTANCE;
if exists (select TABLE_NAME from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'ACT_FO_FORM_DEFINITION') drop table ACT_FO_FORM_DEFINITION;
if exists (select TABLE_NAME from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'ACT_FO_FORM_RESOURCE') drop table ACT_FO_FORM_RESOURCE;
if exists (select TABLE_NAME from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'ACT_FO_FORM_DEPLOYMENT') drop table ACT_FO_FORM_DEPLOYMENT;
